on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v5

      - name: Compute sanitized version
        run: |
          echo VERSION=1.0.${GITHUB_RUN_NUMBER} >> $GITHUB_ENV

      - name: Set up Node.js version
        uses: actions/setup-node@v5
        with:
          node-version: "24.x"

      - name: Install and build
        run: |
          cd src/
          yarn install --frozen-lockfile
          yarn build

      - name: checkout octopus
        uses: OctopusDeploy/install-octopus-cli-action@v3.1.3

      - name: Create client zip
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: atil_feecalculator_client
          version: ${{ env.VERSION }}
          base_path: src/build
          output_folder: ./out
          files: |
            **/*

      - name: Push packages
        uses: OctopusDeploy/push-package-action@v3
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          space: 'Default'
          packages: |
            out/atil_feecalculator_client.${{ env.VERSION }}.zip

      - name: Create release
        uses: OctopusDeploy/create-release-action@v3
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          space: 'Default'
          project: "ATIL - Fee calculator Client"
          release_number: ${{ env.VERSION }}
          channel: ft-prod
