on: 
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: checkout octopus
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.8

      - name: pack & push to octo 
        run: |
          MY_VAR="1.0.${{github.run_number}}"
          octo pack --basePath=./build --id atil_feecalculator_client --version $MY_VAR --outFolder ./out --format zip
          octo push --package "./out/atil_feecalculator_client.${MY_VAR}.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}"

